// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f080e4a7-d621-4805-a356-c01fcc70901d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8lO4Z4xHO",
    "aws_user_pools_web_client_id": "3ccogso9ii6268bqtevi20av9v",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3jkx4xq2ajc27oirj6pmf2yv3m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-55pmlqehynaavcdojv2fuqypiu"
};


export default awsmobile;
